[build]
  publish = "dist"  # Astro 默认输出目录
  command = "npm run build"
  
# 根目录
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

# 文章和页面
[[headers]]
  for = "/*/"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

# HTML 文件
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
    Timing-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CSS 文件
[[headers]]
  for = "/_astro/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Timing-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"

# JS 文件
[[headers]]
  for = "/_astro/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Timing-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Timing-Allow-Origin = "*"

# 字体文件
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Timing-Allow-Origin = "*"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Timing-Allow-Origin = "*"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Timing-Allow-Origin = "*"

# 安全头
[[headers]]
  for = "/*"
  [headers.values]
    Timing-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"